### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ormus7577** [JeffHoogland/qutemtgstats#4]
Hi Jeff,

nice tool, a previous version managed to parse my data, the current one does not.

http://pastebin.com/x74n33wa (note: I'm a german player, paste contains german letters, i've switched to english before copying)

![error](https://cloud.githubusercontent.com/assets/13729724/9169771/c41f8cfc-3f5d-11e5-9726-a531e22ed1a4.JPG)

**Comment by JeffHoogland** [comment]
Can you please share the data post you are using to get this error message? Pastebin.com it or something.

**Comment by ormus7577** [comment]
I did in my original message - or is this the wrong data?

**Comment by JeffHoogland** [comment]
Missed that in my quick response. I'll give this a try within the next few days.

**Comment by JeffHoogland** [comment]
Paste no longer valid on pastebin.com. If you still have it please reopen. Sorry I lost track of this one :-/
