### ISSUE TITLE
Time period filter suggestion

### ISSUE THREAD

**Issue by bobbyleblanc** [JeffHoogland/qutemtgstats#6]
When filtering through time periods, it would be nice if you can't see decks that don't show up during that period. The same is true for events and formats. Another small thing is, I made a typo at one point and now that deck name is permanently saved in my list of decks, even though it was removed. Shouldn't stay if removed from the events tab. The same is also true for event names. Great tool overall!

**Comment by JeffHoogland** [comment]
Resolved via https://github.com/JeffHoogland/qutemtgstats/commit/f492b7663d5c0c06db6abb072f8a8c2a7b932919
