### ISSUE TITLE
Error while executing command in the console

### ISSUE THREAD

**Issue by mmohr1** [JeffHoogland/qutemtgstats#7]
Hey Jeff,

I tried to run the code in Chrome but I got this error:

VM196:2 Uncaught TypeError: Cannot read property 'click' of null
    at <anonymous>:2:14(anonymous function) @ VM196:2

Mike Mohr

**Comment by JeffHoogland** [comment]
Which code are you running in Chrome? Are you on the events page for your PWP history when doing so?
